### ISSUE TITLE
real scene defocus dataset issue

### ISSUE THREAD

**Issue by dogyoonlee** [limacv/Deblur-NeRF#13]
Hello, 

I wonder the real scene defocus dataset.

For sausage scene, I think there are lack of consistency for train data and test data.

This lead to remarkable performance drop at that scene, especially.

Therefore, I think sausage scene is excluded finally.

In addition, the number of real scene defocus dataset is 11.

As you mentioned in your paper, there should be 10 camera motion blur and 10 defocus blur dataset for real scene.

If you don't mind, could you let me know which scene is excluded in real scene defocus dataset?

Thank you

**Comment by dogyoonlee** [comment]
In addition, 
for defocus bush dataset,

llffhold value is set to 13.

However, index 0, 13, 26, 39 is not seems to be ground truth.

how did you set and get quantitative results for real scene?

**Comment by limacv** [comment]
As you've found, the bush dataset has all views blurry. So we excluded the bush dataset. And since the GT in the real scene defocus dataset is not the actual "ground truth" (which is impossible to get due to the change of aperture), so the numerical results are provided just for reference only.
