### ISSUE TITLE
Evaluation with trained model weight

### ISSUE THREAD

**Issue by dogyoonlee** [limacv/Deblur-NeRF#2]
I really appreciate to your awesome work!

I wonder do you have any specific evaluation code with trained model weight?

Could you share the code if you have?

**Comment by limacv** [comment]
邮件已送达 马力的邮箱

**Comment by Mercury1010** [comment]
I have the same question, Could you send me one, really appreciate it! 
Here is my email adress: Mercuryxzh@163.com

**Comment by Mercury1010** [comment]
> 邮件已送达 马力的邮箱
I have the same question, Could you send me one, really appreciate it!
Here is my email adress: [Mercuryxzh@163.com](mailto:Mercuryxzh@163.com)

**Comment by limacv** [comment]
The evaluation code lies inside the run_nerf.py together with the training code [here](https://github.com/limacv/Deblur-NeRF/blob/495b2632c4d6af176f8f2a56884f4004e7e0414c/run_nerf.py#L595). To render video or test views, you can also call the run_nerf.py with `--render_only` args. The pretrained model weight will be released in the dataset folder in a few days. Thanks!

**Comment by dogyoonlee** [comment]
@limacv Thanks a lot!
By the way, can I ask a question about quantitative results in your paper?
For the Table 1 in your paper, How many kernel point was used to produce the best results?
Are the results produced by the model whose kernel points are 5 or more? (probably, 10~12?)

It will be really helpful to me if you let me know!

Again, I really appreciate to your awesome work and congratulate acceptance to CVPR!

**Comment by limacv** [comment]
All of the results shown in the paper (except the ablation on the kernel point) use 5. But as the ablation shows, more points lead to better quality. So it is really just a trade-off between the training time and the quality.

**Comment by dogyoonlee** [comment]
@limacv I get it.
Then as I understand, for example, the best results of tanabata scene(camera motion) which is represented as 27.11 is the performance of deblur-nerf with kernel point 5. 
Is that right?

![image](https://user-images.githubusercontent.com/62277785/175879072-43714914-0a77-4e5e-8148-7cf0053f4a61.png)

That means the results on dotted green line(kernel point 5) of middle camera motion blur in following table is not tanabata scene.

![image](https://user-images.githubusercontent.com/62277785/175879399-522d156b-f221-4e6b-b481-786caf1cebe6.png)

Could you let me know which scenes are used on above table, respectively?( Small, Middle, Large )

**Comment by limacv** [comment]
Yes, and this ablation uses the _FACTORY_ scene, but we re-synthesize the blur in Blender under different settings. Basically, we synthesize different degrees of blur to conduct the ablations, so the PSNR and the SSIM are inconsistent with Table 1.

**Comment by dogyoonlee** [comment]
@limacv That's really helpful information.
Thank you again!! :)
