### ISSUE TITLE
急求：关于参数的问题

### ISSUE THREAD

**Issue by luckhui0505** [limacv/Deblur-NeRF#29]
作者您好，想咨询一下关于代码中问题，在代码class DSKnet中设置的  optim_trans=False, optim_spatialvariant_trans=False，第一个参数是在对应的4.3节，第二个参数也是对光线原点的优化，论文中有所介绍，但是代码中为什么设置成FALSE？

**Comment by limacv** [comment]
it's set to true in the config file

**Comment by luckhui0505** [comment]
并没发现在配置文件中对这两个参数设置为true,是我要重新在您的参数文件中加入这两个参数的赋值吗?

**Comment by luckhui0505** [comment]
似乎我用默认的参数跑出来的结果跟论文差不多，但我没在配置文件中设置这两个参数，这是怎么回事呢？

**Comment by luckhui0505** [comment]
已经解决
