### ISSUE TITLE
How to generate the error maps in the paper？

### ISSUE THREAD

**Issue by chenghao-li-1029** [limacv/Deblur-NeRF#31]
![image](https://github.com/limacv/Deblur-NeRF/assets/26246729/83a9d551-bf77-48ab-bf4a-dfed31c09cdc)
Hi~ I'm wondering how to generate the error maps provided in the paper. Is there a sample code? Or just thresholding on the mse map?

**Comment by limacv** [comment]
Yes, we thresholding the mse map, normalizing to [0, 1], and color mapping the error with cv.COLORMAP_HOT
