### ISSUE TITLE
关于blender文件

### ISSUE THREAD

**Issue by zouchen92** [limacv/Deblur-NeRF#32]
您好

我利用您所提供的blender文件，运行export_blur生成了每个模糊视角下的10张清晰的图片

我将10张图片合并求平均来合成模糊的图片，请问是这样的操作是对的吗
![image](https://github.com/limacv/Deblur-NeRF/assets/113101207/6ecf35ea-73f1-4566-b7c1-49980292b8fe)

**Comment by limacv** [comment]
我是先将图片从srgb转成linear，在linear空间平均，再转成srgb

**Comment by zouchen92** [comment]
感谢您的回复
