### ISSUE TITLE
The function visualize_pose missing

### ISSUE THREAD

**Issue by BeileiCui** [limacv/Deblur-NeRF#33]
Dear author,

Thanks for your wonderful work first! I am trying to visualization of the proposed method but found that the function [visualiza_pose](https://github.com/limacv/Deblur-NeRF/blob/master/run_nerf_helpers.py#L165C32-L165C32) is missing. Could you please update the function?

Best,
Beilei

**Comment by limacv** [comment]
This function is not used by the pipeline. You can safely remove this function.
