### ISSUE TITLE
config参数rmnearplane每个场景不一样

### ISSUE THREAD

**Issue by xianrui-luo** [limacv/Deblur-NeRF#35]
你好，请问一下为什么config文件对于每个场景的render_rmnearplane参数都有区别，是经过调参选择效果最好的吗？

**Comment by limacv** [comment]
是的，这一步是为了去除一些floater。当然目前有一些新的去除floater的工作可以借鉴。这里用的是一个非常粗暴简单的方法。

**Comment by xianrui-luo** [comment]
谢谢解答
