### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by lbh666** [limacv/Deblur-NeRF#36]
Hi, thanks for your amazing work. 
I plan to build my own scenes (free camera trajectory) in blender. I wonder if you build these models by yourself. If not, where can I find such good quality 3d models such as outdoorpool and tanabata model? If so, is there any tutorials of blender suit for newbee like me :)
Looking forward to your early reply.

**Comment by limacv** [comment]
I find most of these amazing 3D models from Sketchfab. And it may take a while to find free, nice 3D assets. I should have cited the authors of these 3D models. But if you are generous enough, you can always purchase good assets from various 3D assets stores and save a lot of time : )

**Comment by lbh666** [comment]
Got It, Thanks
