### ISSUE TITLE
Which is the 'Trolley' data in the synthetic defocus dataset？

### ISSUE THREAD

**Issue by rongduo** [limacv/Deblur-NeRF#39]
I downloaded the synthetic defocus blur dataset, but I didn't find the data sample that is named 'Trolley'. Is it actually the data sampled named 'wine' in the dataset?

**Comment by limacv** [comment]
Yes, sorry for the confusion

**Comment by rongduo** [comment]
> Yes, sorry for the confusion

Thanks  a lot for your quick response~
