### ISSUE TITLE
关于代码中参数问题

### ISSUE THREAD

**Issue by luckhui0505** [limacv/Deblur-NeRF#40]
您好，请问代码中有两个参数，optim_trans和optim_spatialvariant_trans。这两个参数都是表示源点的优化，有什么区别呢？或者是为什么设置两个参数呢？

**Comment by limacv** [comment]
optim_trans是对于某个view优化一个整体的camera center translation。optim_spatialvariant_trans是对于每个pixel优化一个单独的ray origin translation。有两个是因为实验的时候试了两种优化方式（但是没有在论文中展现）。
