### ISSUE TITLE
trained algorithm successfully on LLFF synthetic dataset, albeit with a slightly blurry neural radiance field

### ISSUE THREAD

**Issue by addy1997** [limacv/Deblur-NeRF#8]
Hi @limacv, 

I trained your algorithm on this LLFF synthetic dataset. please find the video below for your reference. 

https://user-images.githubusercontent.com/29406906/179422063-c1e9bba7-70bb-42ce-961e-093840a7bf34.mp4

I have a query, what was your approach for deriving the DSK or deformable space kernel. 

Were there any relevant papers available on DSK?

thanks
Adwait

**Comment by 1Unicorn2** [comment]
您好，想问您使用自己数据集的时候，是否出现所有map参数都是NAN的情况？
